Try 7

diff --git a/.github/workflows/fast_tests.yml b/.github/workflows/fast_tests.yml
--- a/.github/workflows/fast_tests.yml
+++ b/.github/workflows/fast_tests.yml
@@ -2,8 +2,6 @@ name: Unit and integration tests (On-Prem)
 
 on:
   workflow_dispatch:
-  push:
-    branches: [ main ]
   pull_request:
     branches: [ main ]
 
@@ -18,22 +16,25 @@ jobs:
     name: Run tests
     runs-on: [self-hosted, hpu]
     steps:
-      - name: 'Cleanup build folder'
-        run: |
-          ls -la ./
-          sudo rm -rf ./* || true
-          sudo rm -rf ./.??* || true
-          ls -la ./
-      - name: Checkout
-        uses: actions/checkout@v2
+      # - name: 'Cleanup build folder'
+      #   run: |
+      #     ls -la ./
+      #     sudo rm -rf ./* || true
+      #     sudo rm -rf ./.??* || true
+      #     ls -la ./
+      # - name: Checkout
+      #   uses: actions/checkout@v2
       - name: Pull image
         run: |
           docker pull vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:1.5.0-610
+      # - name: Blabla
+      #   run: |
+      #     docker run
       - name: Run tests
         run: |
           docker run \
           -v $PWD:/root/workspace \
-          --workdir=/root/workspace/optimum-habana \
+          --workdir=/root/workspace \
           --runtime=habana \
           -e HABANA_VISIBLE_DEVICES=all \
           -e OMPI_MCA_btl_vader_single_copy_mechanism=none \
@@ -41,4 +42,4 @@ jobs:
           --net=host \
           --ipc=host \
           vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:1.5.0-610 \
-          /bin/bash tests/ci/fast_tests.sh
+          git clone https://github.com/huggingface/optimum-habana.git && cd optimum-habana && git checkout ${{ github.event.pull_request.head.sha }} && /bin/bash tests/ci/fast_tests.sh
